name: flutter

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  buld-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.24.0'

      - name: Install Dependencies
        run: flutter pub get

      - name: Build docker image
        run : docker build -t lytis .